---
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "activesupport"
        versions:
          - ">=6.0.0"
      - dependency-name: "google-api-client"
        versions:
          - ">=0.36"
      - dependency-name: "googleauth"
        versions:
          - ">=0.12"
